
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: adm
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
